import React, { useState } from 'react';
import { View, Text, ScrollView, Pressable } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useWorkspace } from '@/context/WorkspaceContext';
import { ChevronLeft, Trash2, Play, History, CheckCircle2, Bookmark } from 'lucide-react-native';

export default function ResearchHistoryScreen() {
  const navigation = useNavigation<any>();
  const { savedItems, unsaveItem } = useWorkspace();
  
  // Filter only items that are type 'research'
  const history = savedItems.filter(item => item.type === 'research').sort((a, b) => 
    new Date(b.savedAt).getTime() - new Date(a.savedAt).getTime()
  );

  const handleDelete = (id: string) => {
    unsaveItem(id);
  };

  const formatDate = (isoStr: string) => {
    try {
      const d = new Date(isoStr);
      return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
    } catch (e) {
      return isoStr;
    }
  };

  return (
    <View className="flex-1 bg-background">
      <View className="px-4 py-4 bg-surface border-b border-outline-variant flex-row items-center shadow-sm z-10 sticky top-0">
        <Pressable onPress={() => navigation.goBack()} className="p-2 -ml-2 rounded-full flex-row items-center">
          <ChevronLeft size={24} color="#5f6368" />
          <Text className="text-[16px] font-bold text-primary ml-1">Menu</Text>
        </Pressable>
      </View>

      <ScrollView className="flex-1 p-4">
        <View className="mb-6">
          <Text className="text-[28px] font-bold text-primary mb-2">Research History</Text>
          <Text className="text-[14px] text-on-surface-variant">View your past queries and insights generated by AI Sathi. You can resume any research thread or delete old queries.</Text>
        </View>

        {history.length === 0 ? (
          <View className="flex-1 items-center justify-center py-20 bg-surface-container-low rounded-2xl border border-outline-variant/30">
            <History size={48} color="#5f6368" className="mb-4 opacity-50" />
            <Text className="text-[18px] font-bold text-primary mb-2">No research history</Text>
            <Text className="text-[14px] text-on-surface-variant text-center px-6 mb-6">
              Your past AI Sathi interactions will appear here.
            </Text>
            <Pressable onPress={() => navigation.navigate('MainTabs', { screen: 'AISathi' })} className="px-6 py-3 bg-primary rounded-xl flex-row items-center gap-2">
              <Play size={18} color="#ffffff" />
              <Text className="text-white font-bold">Start New Research</Text>
            </Pressable>
          </View>
        ) : (
          <View className="gap-4 pb-10">
            {history.map((item) => (
              <View key={item.id} className="bg-surface rounded-2xl border border-outline-variant/50 p-5 shadow-sm">
                <View className="flex-row items-center gap-2 mb-3">
                  <View className="bg-surface-container px-2 py-1 rounded flex-row items-center gap-1">
                    <Bookmark size={12} color="#4a4643" />
                    <Text className="text-[11px] font-mono text-on-surface-variant uppercase">{item.label}</Text>
                  </View>
                  <Text className="text-[12px] text-on-surface-variant font-bold">{formatDate(item.savedAt)}</Text>
                  <CheckCircle2 size={14} color="#138808" className="ml-auto" />
                </View>
                
                <Text className="text-[16px] font-bold text-primary mb-4 leading-6">{item.title}</Text>
                
                <View className="flex-row items-center justify-between mt-2 pt-4 border-t border-surface-container-low">
                  <Pressable onPress={() => handleDelete(item.id)} className="flex-row items-center gap-2 px-3 py-2 rounded-lg bg-[#ffdad6]">
                    <Trash2 size={16} color="#ba1a1a" />
                    <Text className="text-[13px] font-bold text-[#ba1a1a]">Delete</Text>
                  </Pressable>
                  <Pressable onPress={() => navigation.navigate('MainTabs', { screen: 'AISathi', params: { q: item.title } })} className="flex-row items-center gap-2 px-4 py-2 rounded-lg bg-primary">
                    <Play size={16} color="#ffffff" />
                    <Text className="text-[13px] font-bold text-white">Resume</Text>
                  </Pressable>
                </View>
              </View>
            ))}
          </View>
        )}
      </ScrollView>
    </View>
  );
}
