import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { TranslatingText } from '@/components/common/TranslatingText';

interface HistoryItem {
  id: string;
  query: string;
  date: string;
  status: 'Complete' | 'Failed';
}

const MOCK_HISTORY: HistoryItem[] = [
  { id: 'H-001', query: 'What is the certification process for lithium-ion batteries under IS 16046?', date: '2025-09-10T10:30:00Z', status: 'Complete' },
  { id: 'H-002', query: 'List all mandatory tests for Toys under QCO 2020.', date: '2025-09-08T14:15:00Z', status: 'Complete' },
  { id: 'H-003', query: 'Can an importer apply for CRS registration directly?', date: '2025-09-05T09:45:00Z', status: 'Complete' },
];

export default function ResearchHistory() {
  const [history, setHistory] = useState(MOCK_HISTORY);

  const handleDelete = (id: string) => {
    setHistory(history.filter(h => h.id !== id));
  };

  const formatDate = (isoStr: string) => {
    const d = new Date(isoStr);
    return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
  };

  return (
    <div className="w-full max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <div className="mb-8 border-b border-outline-variant/30 pb-6">
        <h1 className="text-h1 font-serif-hero text-on-surface mb-2">
          <TranslatingText text="Research History" />
        </h1>
        <p className="text-body-fluid text-on-surface-variant max-w-2xl">
          <TranslatingText text="View your past queries and insights generated by AI Sathi. You can resume any research thread or delete old queries." />
        </p>
      </div>

      {history.length === 0 ? (
        <div className="text-center py-20 bg-surface-container-lowest rounded-2xl border border-outline-variant/30">
          <span className="material-symbols-outlined text-[48px] text-on-surface-variant/40 mb-4">history</span>
          <h3 className="text-h2 font-semibold text-on-surface mb-2">
            <TranslatingText text="No research history" />
          </h3>
          <p className="text-on-surface-variant mb-6">
            <TranslatingText text="Your past AI Sathi interactions will appear here." />
          </p>
          <Link to="/ai-sathi" className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary text-white rounded-xl font-medium hover:bg-primary-hover transition-colors">
            <span className="material-symbols-outlined text-[20px]">auto_awesome</span>
            <TranslatingText text="Start New Research" />
          </Link>
        </div>
      ) : (
        <div className="grid gap-4">
          {history.map((item, i) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="group relative flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-surface-container-lowest border border-outline-variant/30 hover:border-primary/30 transition-all shadow-[0_4px_12px_rgba(0,0,0,0.02)] hover:shadow-[0_8px_24px_rgba(0,0,0,0.06)]"
            >
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-[12px] font-mono text-on-surface-variant bg-surface-container px-2 py-0.5 rounded">
                    {item.id}
                  </span>
                  <span className="text-[12px] text-on-surface-variant font-medium">
                    {formatDate(item.date)}
                  </span>
                  {item.status === 'Complete' && (
                    <span className="w-1.5 h-1.5 rounded-full bg-status-verified ml-1" title="Complete" />
                  )}
                </div>
                <h3 className="text-[15px] sm:text-[16px] font-medium text-on-surface line-clamp-2 pr-8 sm:pr-0">
                  <TranslatingText text={item.query} />
                </h3>
              </div>

              <div className="flex items-center gap-2 sm:opacity-0 group-hover:opacity-100 transition-opacity self-end sm:self-auto shrink-0 mt-2 sm:mt-0">
                <button
                  onClick={() => handleDelete(item.id)}
                  className="flex items-center gap-2 px-3 py-2 rounded-lg text-[13px] font-medium text-error hover:bg-error/10 transition-colors"
                >
                  <span className="material-symbols-outlined text-[18px]">delete</span>
                  <span className="sm:hidden"><TranslatingText text="Delete" /></span>
                </button>
                <Link
                  to={`/ai-sathi?q=${encodeURIComponent(item.query)}`}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg text-[13px] font-medium bg-primary text-white hover:bg-primary-hover transition-colors"
                >
                  <span className="material-symbols-outlined text-[18px]">resume</span>
                  <TranslatingText text="Resume" />
                </Link>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}
